### ISSUE TITLE
Do you think HGTector is suitable for a Candidate phylum with only 4 draft genomes obtained via metagenome binning?

### ISSUE THREAD

**Issue by yoyohashao** [DittmarLab/HGTector#1]
Hello, I was just wondering if it's necessary to perform HGT search on a Candidate phylum. In my opinion, I thought HGT search should be based on the taxa with clear phylogenetic boundaries and nice representatives. The genomes I am dealing with are a Candidate phylum 'Tectomicrobia' (yet in NCBI taxonomy, it's still a genus in deltaproteobacteria, taxid 93171). All available genomes are from metagenomes (lots of hypothetical proteins, 70-90% completeness). Do you think it's viable to find HGT events in these genomes? 

Also, HGTector seems to be unable to recognize the taxid:
Enter the TaxID of v42, or press Enter if you don't know:91371
Warning: Invalid TaxID: <?xml version="1.0"?>
<!DOCTYPE TaxaSet PUBLIC "-//NLM//DTD Taxon, 14th January 2002//EN" "http://www.ncbi.nlm.nih.gov/entrez/query/DTD/taxon.dtd"> </TaxaSet>.
It's 2016 now and the taxaset was based on 2002 version.

My another question is about the databaser.py, I haven't tested this script due to some disk space issue. I want to know if it will generate the database compatible with RAPsearch/DIAMOND and the peak space usage of databaser.py.

Thanks. 

Kind,Fang

**Comment by qiyunzhu** [comment]
Hello Fang,

Thanks for your interest in our program! I think the taxonomy parsing issue
is due to the frequently updated NCBI records, which may contain format
errors, or new features that our program cannot recognize. Therefore
deploying a local database is recommended. If you use databaser.py to
generate the local database, as of Oct 2015, the disk space usage is 15.4
GB for BLAST, 12.9 GB for DIAMOND and I don't know how much for RAPsearch2
(but should be larger than DIAMOND, according to my experience). Besides
there is a 200 MB taxdump and a 500 MB GI-to-TaxID dictionary. I hope they
are not too much for your disk quote.

Attached please find a development version of searcher.pl, which should run
DIAMOND and RAPSearch2 way faster than the older version. Have fun.

Let me think about your other question and get back to you soon.

Best,
Qiyun

**Comment by yoyohashao** [comment]
Thanks for the reply Qiyun. Can you re-upload the new searcher.pl? I didn't see it in the attachment. Also, if I download a master fasta, it can be reformatted by blastall/rapsearch/diamond right? I am fan of Rapsearch. But I wasn't be able to figure out how to build taxdump. So tonight I will try to download the master fasta then try rapsearch.

**Comment by qiyunzhu** [comment]
Hello Fang,

I just noticed that you are emailing thru the Github, which may not allow
attachment. May I contact you via direct email? Mine is qiyunzhu@gmail.com.
You are right. Once you get the master fasta file, you can reformat it into
Rapsearch format.

Best,
Qiyun
