### ISSUE TITLE
Can't download the genomes from NCBI via the databaser.py

### ISSUE THREAD

**Issue by houjialin** [DittmarLab/HGTector#11]
Dear Qiyun Zhu:
    I was trying to build a database automatically through the databaser.py but it can't work after downloaded the genome list, none of genomes were downloaded.  error like:

Connecting to the NCBI FTP server... done.
Downloading the NCBI taxonomy database... done.
Reading the NCBI taxonomy database... done.
  1585409 taxa read.
Downloading the NCBI representative genome list... done.
Reading the NCBI representative genome list... done.
  4380  genomes read.
Reading RefSeq genome list... done.
  84212 genomes read.
Subsampling genomes... done.
  13254 genomes retained.
Reading RefSeq genomic data... done.
  0 genomes to download.
Extracting non-redundant proteomic data from NCBI RefSeq...
  done.
  0 genomes, 0 protein sequences, and 0 residues downloaded.
  0 proteins extracted.
Task completed.

 could you help me solve this problem? thank you very much.

**Comment by qiyunzhu** [comment]
Hi @houjialin , sorry for the late reply. Recently another person had the same problem, but as I tested from my side everything was fine. So eventually I sent him the entire database I created (~8GB). I can do the same favor to you. My email is `qiyunzhu@gmail.com`. Please let me know yours so that I can send it to you via pCloud.
