### ISSUE TITLE
analyze fails when product empty

### ISSUE THREAD

**Issue by surh** [DittmarLab/HGTector#57]
I was trying to `hgtector analyze` after running search with a custom database. My database has no product information so my search results look like:

```
# ID: S0000001
# Length: 729
# Product: 
# Score: 1499.6
# Hits: 116
WP_135038321.1  99.2    0.0e+00 1489.9  100.0   85831
WP_167961307.1  96.2    0.0e+00 1450.6  100.0   2715212
WP_073346841.1  95.5    0.0e+00 1441.0  100.0   1871006
WP_008998151.1  93.7    0.0e+00 1424.5  100.0   556259
```
This caused a weird error asking me to specify taxonomy even when I had passed both `--self-tax` and `--input-tax`. After some detective work I figured out that the regular expression supposed to match the comment lines does not match my empty product line in the lines below:

https://github.com/DittmarLab/HGTector/blob/8f1c449f4b6fef4aad6361cc1a368362982bb243/hgtector/analyze.py#L275-L280

That happens because the `line.rstrip()` instruction removes the trailing whitespace in my product line, preventing the following`p.match(line)` from actually matching the line. 

It can be solved in several ways, In my case I just specified that rstrip should only remove trailing breaklines by changing line 279 to: `line = line.rstrip("\n")`

**Comment by qiyunzhu** [comment]
@surh Thank you for reporting this issue as well as your solution! It immediately looks reasonable to me because I recently encountered the same issue in another software project, when I was removing `\r\n` from `str.strip`, thinking that Python 3 is smart enought to parse newline encodings but it isn't because all white spaces including ` ` and `\t` will get removed. This may also explain another issue (#55). I will review your pull request and get back to you!
